# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x14\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\rPersonDetails\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2?\n\rPersonService\x12.\n\tGetPerson\x12\x0b.api.Person\x1a\x12.api.PersonDetails\"\x00\x42\rZ\x0bgo_grpc/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013go_grpc/api'
  _globals['_PERSON']._serialized_start=18
  _globals['_PERSON']._serialized_end=38
  _globals['_PERSONDETAILS']._serialized_start=40
  _globals['_PERSONDETAILS']._serialized_end=96
  _globals['_PERSONSERVICE']._serialized_start=98
  _globals['_PERSONSERVICE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
